stages:
  - test
  - build
  - deploy

test:
  image: node:10
  stage: test
  script:
    - npm --no-color ci
    - npm test

build:
  image: node:10
  stage: build
  variables:
    GENERATE_SOURCEMAP: 'false'
  artifacts:
    expire_in: 3 days
    paths:
      - build/
  script:
    - npm --no-color ci
    - npm run build

publish:
  image: docker:stable
  stage: deploy
  dependencies:
    - build
  services:
    - docker:dind
  only:
    - master
  variables:
    IMAGE: mobileteam/swec-planner
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$IMAGE:latest .
    - docker push $CI_REGISTRY/$IMAGE:latest

publish-feature:
  image: docker:stable
  stage: deploy
  dependencies:
    - build
  services:
    - docker:dind
  only:
    - web
  variables:
    IMAGE: mobileteam/swec-planner
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY/$IMAGE:$CI_COMMIT_REF_NAME
